print("Karun Teja Kasturi - GITAM University, Bengaluru")
print("Karun Teja Kasturi - GITAM University, Bengaluru")
print("Karun Teja Kasturi - GITAM University, Bengaluru")
print("Karun Teja Kasturi - GITAM University, Bengaluru")
print("Karun Teja Kasturi - GITAM University, Bengaluru")
